In [7]:
# library import
from utils import ingestion

### 1. INGEST PRICE OF TESLA STOCK

In [10]:
# Ingestion flow
# Major stocks in US market 
stock_to_ingest = ["NVDA", "MSFT", "AAPL", "GOOGL", "AMZN", "META", "AVGO", "TSLA", "JPM"]

# Ingest data
final_df = pd.DataFrame()
for stock in stock_to_ingest: 
    print(f"Ingesting price data for {stock} ...")        
    # append to final_df
    df_temp = ingestion.us_stock_price_yahoo_finance(stock)
    final_df = pd.concat([final_df, df_temp], ignore_index=True)
    print(f"Complete for stock {stock} ...\n")
display(final_df)

Ingesting price data for NVDA ...
Complete for stock NVDA ...

Ingesting price data for MSFT ...
Complete for stock MSFT ...

Ingesting price data for AAPL ...
Complete for stock AAPL ...

Ingesting price data for GOOGL ...
Complete for stock GOOGL ...

Ingesting price data for AMZN ...
Complete for stock AMZN ...

Ingesting price data for META ...
Complete for stock META ...

Ingesting price data for AVGO ...
Complete for stock AVGO ...

Ingesting price data for TSLA ...
Complete for stock TSLA ...

Ingesting price data for JPM ...
Complete for stock JPM ...

,timestamp,open,high,low,close,adjclose,volume,datetime,year,month,day,ticker,table_name
0,2009-12-30 14:30:00,0.454750,0.469500,0.451500,0.466750,0.427956,704008000,20091230,2009,12,30,NVDA,us_stock_price_yahoo_finance
1,2009-12-31 14:30:00,0.467750,0.473750,0.466500,0.467000,0.428186,700340000,20091231,2009,12,31,NVDA,us_stock_price_yahoo_finance
2,2010-01-04 14:30:00,0.462750,0.465500,0.452750,0.462250,0.423830,800204000,20100104,2010,1,4,NVDA,us_stock_price_yahoo_finance
3,2010-01-05 14:30:00,0.460500,0.474000,0.460500,0.469000,0.430019,728648000,20100105,2010,1,5,NVDA,us_stock_price_yahoo_finance
4,2010-01-06 14:30:00,0.468750,0.473000,0.464250,0.472000,0.432770,649168000,20100106,2010,1,6,NVDA,us_stock_price_yahoo_finance
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34730,2025-08-22 13:30:00,293.200012,297.160004,290.130005,296.239990,296.239990,8552800,20250822,2025,8,22,JPM,us_stock_price_yahoo_finance
34731,2025-08-25 13:30:00,296.239990,297.350006,294.140015,294.899994,294.899994,5856300,20250825,2025,8,25,JPM,us_stock_price_yahoo_finance
34732,2025-08-26 13:30:00,294.160004,298.739990,293.500000,298.570007,298.570007,6714700,20250826,2025,8,26,JPM,us_stock_price_yahoo_finance
34733,2025-08-27 13:30:00,297.250000,301.070007,297.040009,299.279999,299.279999,6056500,20250827,2025,8,27,JPM,us_stock_price_yahoo_finance
34734,2025-08-28 13:30:00,300.019989,301.239990,298.700012,301.070007,301.070007,6410500,20250828,2025,8,28,JPM,us_stock_price_yahoo_finance

In [15]:
final_df.to_csv("data/price/us_stock_price_yahoo_finance_top10.csv")

### 2. INGEST NEWS OF TESLA STOCK